//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimpySoftwareNewTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CampaignActivities = new HashSet<CampaignActivity>();
            this.Campaigns = new HashSet<Campaign>();
            this.Genres = new HashSet<Genre>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string ContactName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string TownCity { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> UserId { get; set; }
        public string website { get; set; }
        public string Region { get; set; }
    
        public virtual ICollection<CampaignActivity> CampaignActivities { get; set; }
        public virtual Category Category { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
