//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimpySoftwareNewTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.Companies = new HashSet<Company>();
            this.Genres = new HashSet<Genre>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Country { get; set; }
        public string BandArtist { get; set; }
        public string Company { get; set; }
    
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
